bump min WP and PHP versions
10up/simple-page-ordering pull request #111
Opened 2022-10-30 09:31 UTC by Sidsector9

### Description of the Change

Closes #102

### How to test the Change

### Changelog Entry

> Changed - Bump minimum version to 7.4
> Changed - Bump minimum WordPress version from 3.8 to 5.7

### Credits

Props @vikrampm1 @Sidsector9 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-10-31 15:10 UTC, cadic submitted a review, later dismissed

2022-10-31 16:15 UTC, ravinderk commented
@Sidsector9 do you think we can also add PHP version in composer config: https://getcomposer.org/doc/06-config.md#platform

2022-11-02 08:52 UTC, cadic requested changes
The `.nvmrc` file is empty, shouldn't we specify Node version?

2022-11-07 09:48 UTC, cadic requested changes
@Sidsector9 After the latest change, both 3 e2e test workflows fail at the "Build" step, which looks unsafe for the future automated release workflows. Could you please check what was going wrong there?

2023-01-17 12:31 UTC, cadic approved these changes

2023-01-17 12:32 UTC, merged