Feature/rest api reordering post
10up/simple-page-ordering pull request #74
Opened 2021-10-12 05:19 UTC by ciprianimike

### Description of the Change

The function `ajax_simple_page_ordering()` is the callback function of the AJAX call, it was also responsible for saving the position of the posts.

A refactor has been done, moving the sorting and posts updating part into a new `page_ordering()` function.

The REST endpoint has been added: `wp-json/simplepageordering/v1/page_ordering/`

The `rest_page_ordering()` function has been added as callback for the new REST endpoint and it calls the `page_ordering()` function.

`page_ordering()` is therefore the part of the code where the sorting of post takes place and this is now called via AJAX or REST.

### Verification Process

after taking some of the code out of the ajax_simple_page_ordering () function, I made sure that the operation remained intact, verifying the parameters sent in the request before the refactor and replicating them after the refactor.

I then sent the same parameters through the new REST endpoint and verified that the reordering is consistent, the same parameters via AJAX or REST must lead to the usual sorting results.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

https://github.com/10up/simple-page-ordering/issues/67

2021-10-12 12:28 UTC, lkraav commented on simple-page-ordering.php
> +				'simplepageordering/v1',
Is hyphenless the current REST API namespace convention?

I would expect it to mirror plugin name, like `simple-page-ordering`.

Looking at my large production site `/wp-json/` routes list, most if not all plugins do seem to register their namespaces in human readable form like `/wp-json/ithemes-security`

2021-10-13 14:16 UTC, cadic requested changes

2021-10-13 14:16 UTC, cadic commented on simple-page-ordering.php
> +				wp_send_json_error();
REST Callback [expected to return the result](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#return-value) of the action instead of error processing or output inside the callback function. If an error happens, we need to return `new WP_Error( ... )`
> Importantly, a REST API route’s callback should always return data; it shouldn’t attempt to send the response body itself.

2021-10-13 14:16 UTC, cadic commented on simple-page-ordering.php
> +			wp_send_json_error();
After successful processing, REST endpoint callback expected to return [WP_REST_Response](https://developer.wordpress.org/reference/classes/wp_rest_response/)

2021-10-13 14:24 UTC, cadic commented on simple-page-ordering.php
> +			$excluded = empty( $excluded ) ? array( $post_id ) : array_filter( (array) json_decode( $excluded ), 'intval' ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
Is this second validation really necessary after validating $_POST arguments in `ajax_simple_page_ordering()`?

2021-10-13 14:24 UTC, cadic commented on simple-page-ordering.php
> +			$excluded = empty( $_GET['excluded'] ) ? array( $_GET['id'] ) : array_filter( (array) json_decode( $_GET['excluded'] ), 'intval' ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.Input
[REST arguments](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#arguments) are passed to the callback as a single argument `rest_page_ordering(  WP_REST_Request $request )` and should be accessed as incoming array values, not from $_GET or $_POST.

2021-10-13 14:34 UTC, cadic commented on simple-page-ordering.php
> +				'simplepageordering/v1',
[Naming convention](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#namespacing) recommends to use theme/plugin slug as `vendor` name of the endpoint but there is no strict requirement to use hyphenated or CamelCase.

In this case, since it's the first REST endpoint in this plugin, would be nice to have consistent `simple-page-ordering` vendor name in the route, same as plugin slug and textdomain.

2021-10-14 10:20 UTC, lkraav commented on simple-page-ordering.php
> +			$excluded = empty( $_GET['excluded'] ) ? array( $_GET['id'] ) : array_filter( (array) json_decode( $_GET['excluded'] ), 'intval' ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.Input
Also, many PHPCS rulesets advise using `filter_input()` instead of accessing request globals directly.

2021-10-21 09:14 UTC, cadic requested changes
@ciprianimike thank you for the update. There are couple minor changes left and maybe a merge conflict (version bumb and readme files)

2021-10-21 09:14 UTC, cadic commented on readme.txt
> +Tested up to: 5.7
Do we really downshift this from 5.8? Also includes README.md, CREDITS.md and CHANGELOG.md

2021-10-21 09:14 UTC, cadic commented on simple-page-ordering.php
> +		 * @param string $excluded Array of post IDs.
Doc type for `$excluded` seems to be `array`

2021-10-21 09:14 UTC, cadic commented on simple-page-ordering.php
> +			$post_id  = empty( $request->get_param( 'id' ) ) ? false : (int) $request->get_param( 'id' );
To validate, sanitize, specify mandatory arguments and default values we could use `register_rest_route()` at `Simple_Page_Ordering::rest_api_init()` instead of manual handle here.

Please refer to the [REST handbook](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#:~:text=Arguments%20are%20defined%20as%20a%20map%20in%20the%20key%20args%20for%20each%20endpoint)

2021-10-21 09:19 UTC, cadic commented on simple-page-ordering.php
> +			die( wp_json_encode( $result ) );
This is not related to the issue itself, but using `die()` to return AJAX errors and success is obsolete, better to go with `wp_send_json_error()` and `wp_send_json_success()`

2021-10-22 09:49 UTC, ciprianimike commented on simple-page-ordering.php
> +			die( wp_json_encode( $result ) );
I guess it should go to a new issue as it is a practice used elsewhere in this function and we need to check another section of the plugin that has nothing to do with the REST functionality

2021-10-22 09:51 UTC, ciprianimike commented on simple-page-ordering.php
> +			$post_id  = empty( $request->get_param( 'id' ) ) ? false : (int) $request->get_param( 'id' );
we are already using it at L#422
probably this checks are redundant but consistent with the ones done in ajax callback L#145

2021-10-22 09:52 UTC, ciprianimike commented on readme.txt
> +Tested up to: 5.7
merged `develop` into the feature branch, resolved conflicts and added documentation

2021-10-22 13:06 UTC, cadic requested changes

2021-10-22 13:06 UTC, cadic commented on simple-page-ordering.php
> +			$post_id  = empty( $request->get_param( 'id' ) ) ? false : (int) $request->get_param( 'id' );
@ciprianimike at L#422 we only have `description` and `type` for each argument. I mean we could add `required` and `default`. It will help to return detailed error REST responses natively (without manual return like L#462)

2021-10-22 16:18 UTC, ciprianimike commented
@cadic got it, added parameters `required` and `default`

2021-10-25 07:01 UTC, cadic approved these changes
Thanks @ciprianimike, it's a great new feature!

2021-10-26 15:00 UTC, merged